//! streamwm configuration loading (TOML), generated by the dotfiles Nix module.

use serde::Deserialize;

#[derive(Debug, Clone, Deserialize)]
pub struct Config {
    /// Modifier name: "super", "alt", "ctrl" (maps to MOD4/MOD1/CTRL).
    #[serde(default = "default_mod")]
    pub modifier: String,

    /// Terminal command (spawned by the terminal binding).
    #[serde(default = "default_terminal")]
    pub terminal: String,

    /// Launcher command (spawned by the launcher binding, e.g. mod+d).
    #[serde(default = "default_launcher")]
    pub launcher: String,

    /// Gap between windows, logical px.
    #[serde(default = "default_gap")]
    pub gap: u32,

    /// Window border width, logical px.
    #[serde(default = "default_border")]
    pub border_width: u32,

    /// Unfocused border color (RRGGBB).
    #[serde(default = "default_border_color")]
    pub border_color: String,

    /// Focused border color (RRGGBB).
    #[serde(default = "default_focused_border_color")]
    pub focused_border_color: String,

    /// Focus follows mouse (default true).
    #[serde(default = "default_true")]
    pub focus_follows_mouse: bool,

    /// Whether to use server-side decorations (titlebars).
    #[serde(default = "default_true")]
    pub use_ssd: bool,

    /// Keybindings: list of (keysym, modifiers, action).
    #[serde(default)]
    pub bindings: Vec<Binding>,

    /// Lid handling.
    #[serde(default)]
    pub lid: Lid,

    /// Allow arbitrary spawn commands (security guard for status/control clients).
    #[serde(default)]
    pub allow_spawn: bool,
}

#[derive(Debug, Clone, Deserialize)]
pub struct Binding {
    /// xkbcommon keysym name, e.g. "j", "Return", "XF86AudioRaiseVolume".
    pub keysym: String,
    /// Modifiers: comma list of "shift","ctrl","alt","super" or "" for none.
    #[serde(default)]
    pub modifiers: String,
    /// Action, e.g. "focus_next", "spawn".
    pub action: String,
    /// Optional argument (e.g. the command for a "spawn" action, or tag id).
    #[serde(default)]
    pub arg: Option<String>,
}

#[derive(Debug, Clone, Default, Deserialize)]
pub struct Lid {
    /// Enable lid handling at all.
    #[serde(default)]
    pub enable: bool,
    /// kanshi profile to switch to on lid close.
    #[serde(default = "default_lid_close_profile")]
    pub close_profile: String,
    /// kanshi profile to switch to on lid open.
    #[serde(default = "default_lid_open_profile")]
    pub open_profile: String,
}

fn default_mod() -> String {
    "super".to_string()
}
fn default_terminal() -> String {
    "alacritty".to_string()
}
fn default_launcher() -> String {
    "alacritty".to_string()
}
fn default_gap() -> u32 {
    8
}
fn default_border() -> u32 {
    2
}
fn default_border_color() -> String {
    "4c4c4c".to_string()
}
fn default_focused_border_color() -> String {
    "5294e2".to_string()
}
fn default_true() -> bool {
    true
}
fn default_lid_close_profile() -> String {
    "office_clamshell".to_string()
}
fn default_lid_open_profile() -> String {
    "office".to_string()
}

impl Config {
    pub fn load(path: &str) -> Config {
        let text = std::fs::read_to_string(path).unwrap_or_else(|e| {
            log::warn!("failed to read config {path}: {e}; using defaults");
            String::new()
        });
        toml::from_str(&text).unwrap_or_else(|e| {
            log::warn!("failed to parse config {path}: {e}; using defaults");
            Config::default()
        })
    }

    /// Number of tags (fixed 0..=9).
    pub fn num_tags(&self) -> u32 {
        10
    }

    /// Parse a hex color like "4c4c4c" into (r,g,b) 0..255.
    pub fn color(&self, hex: &str) -> (u8, u8, u8) {
        let s = hex.trim_start_matches('#');
        let v = u32::from_str_radix(s, 16).unwrap_or(0);
        (((v >> 16) & 0xff) as u8, ((v >> 8) & 0xff) as u8, (v & 0xff) as u8)
    }
}

impl Default for Config {
    fn default() -> Self {
        Config {
            modifier: default_mod(),
            terminal: default_terminal(),
            launcher: default_launcher(),
            gap: default_gap(),
            border_width: default_border(),
            border_color: default_border_color(),
            focused_border_color: default_focused_border_color(),
            focus_follows_mouse: true,
            use_ssd: true,
            bindings: vec![],
            lid: Lid::default(),
            allow_spawn: true,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_minimal() {
        let c: Config = toml::from_str("modifier = \"super\"\ngap = 4\n").unwrap();
        assert_eq!(c.modifier, "super");
        assert_eq!(c.gap, 4);
        assert_eq!(c.num_tags(), 10);
    }

    #[test]
    fn color_parse() {
        let c = Config::default();
        assert_eq!(c.color("5294e2"), (0x52, 0x94, 0xe2));
        assert_eq!(c.color("#4c4c4c"), (0x4c, 0x4c, 0x4c));
    }
}
